remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Blueprint Metrics Services - A Proposal for Dyrwall Estimating Services]
description: [We are a dedicated construction estimation firm providing precise and reliable cost analysis. Specializing in bid preparation, material takeoffs, and Budget Forecasting. We deliver clear, actionable estimates using the latest industry software.]
